routes/web.php
<?php


Route::get('/', function () {
    $kategori = \App\Kategori::all();
    $potensi = \App\Potensi::with(['kategori', 'gambar'])->get()->toJson();
    // $potensi = $potensi->toJson(JSON_PRETTY_PRINT);

    return view('home', compact('kategori', 'potensi'));
});

Route::group(['prefix' => 'rute'], function() {
    Route::get('masyarakat', 'KunjunganController@masyarakat');
    Route::get('wilayah', 'KunjunganController@wilayah');
    Route::get('pkk1', 'KunjunganController@pkk1');
    Route::get('pkk2', 'KunjunganController@pkk2');
});

Route::resource('/ketik/potensi', 'PotensiController');
Route::resource('/ketik/kategori', 'KategoriController');

app/Potensi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Potensi extends Model
{
    protected $table = 'potensi';
    protected $fillable = [
        'nama', 'pemilik', 'alamat', 'keterangan', 'lat', 'long'
    ];

    public function kategori()
    {
        return $this->belongstoMany('\App\Kategori');
    }

    public function gambar()
    {
        return $this->belongsToMany('\App\Gambar');
    }
}

app/Http/Controllers/PotensiController.php
<?php

namespace App\Http\Controllers;

use App\Potensi;
use App\Gambar;
use App\Kategori;
use Illuminate\Http\Request;
use Intervention\Image\ImageManagerStatic;
use Carbon\Carbon;

class PotensiController extends Controller
{
    protected $potensi;
    protected $image;
    protected $dest;
    protected $gb;
    protected $kategori;

    public function __construct(
        Potensi $potensi,
        ImageManagerStatic $image,
        Gambar $gb,
        Kategori $kategori
    )
    {
        $this->potensi = $potensi;
        $this->kategori = $kategori;
        $this->gb = $gb;
        $this->image = $image;
        $this->dest = public_path('images/upload');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $potensi = $this->potensi->all();

        return view('potensi.index', compact('potensi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategori = $this->kategori->all();

        return view('potensi.create', compact('kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //save potensi untuk mendapatkan potensi id
        $potensi = $this->potensi->create(
            array_except($request->all(), ['kategori', 'gambar'])
        );

        // save relasi potensi dengan kategori_id
        $potensi->kategori()->sync($request->kategori);

        if($request->hasFile('gambar')) {
            $image = $request->file('gambar');

            if (!file_exists($this->dest)) {
                mkdir($this->dest, 666, true);
            }

            foreach($image as $img) {
                $time = Carbon::now();
                $filename = str_random(5).date_format($time,'d').rand(1,9).date_format($time,'h').".jpg";
                $namafile = pathinfo($img->getClientOriginalName(), PATHINFO_FILENAME);
                $images = $this->image->make($img)->save($this->dest.'/'.$filename);

                //simpan gambar ke database;
                $gambar = $this->gb->create([
                    'nama' => $namafile,
                    'files' => $filename
                ]);

                //simpan ke tabel relasi
                $gambar->potensi()->attach($potensi->id);
            }
        }

        return redirect('ketik/potensi');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Potensi  $potensi
     * @return \Illuminate\Http\Response
     */
    public function show(Potensi $potensi)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Potensi  $potensi
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Potensi  $potensi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Potensi  $potensi
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $potensi = $this->potensi->find($id);

        foreach ($potensi->gambar as $value) {
            unlink($this->dest.'/'.$value->files);
            $value->delete();
        }

        $potensi->gambar()->wherePivot('potensi_id', '=', $potensi->id)->detach();
        $potensi->kategori()->wherePivot('potensi_id', '=', $potensi->id)->detach();
        $potensi->delete();

        return redirect('ketik/potensi');
    }
}

resources/views/potensi/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Input Potensi</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{{ asset('css/materialize.min.css') }}"  media="screen,projection"/>
    <link rel="stylesheet" rel="stylesheet" href="{{ asset('css/styles.css') }}">
</head>
<body>

    <div class="container" style="margin-top: 40px;">
       <div class="card-panel">
           <div class="row">
               <span class="card-title">
                   <h5>Input Potensi</h5>
               </span>
                <form class="col s12" action="{{ url('/ketik/potensi') }}" method="post" enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="row">
                    <div class="input-field col s12">
                        <select class="icons" name="kategori[]" multiple>
                            <option value="" disabled selected>Pilih Kategori</option>
                            @if($kategori)
                            @foreach($kategori as $kat)
                            <option value="{{ $kat->id }}" data-icon="{{ asset('images/icons/'.$kat->gambar_icon) }}">{{ $kat->nama }}</option>
                            @endforeach
                            @endif
                        </select>
                        <label>Pilih Kategori Potensinya</label>
                    </div>
                </div>

                <div class="row">
                   <div class="input-field col s6">
                      <input placeholder="Nama Tempat" name="nama" type="text">
                      <label for="nama">Nama Tempat</label>
                   </div>
                   <div class="input-field col s6">
                      <input placeholder="Nama Pemilik" name="pemilik" type="text">
                      <label for="pemilik">Nama Pemilik</label>
                   </div>
                </div>
                <div class="row">
                   <div class="input-field col s12">
                      <input placeholder="Alamat" type="text" name="alamat">
                      <label for="alamat">Alamat</label>
                   </div>
                </div>
                <div class="row">
                   <div class="input-field col s12">
                      <textarea placeholder="Keterangan" id="keterangan" name="keterangan" class="materialize-textarea"></textarea>
                      <label for="keterangan">Keterangan</label>
                   </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                       <input placeholder="Latitude" name="lat" type="text">
                       <label for="lat">Latitude</label>
                    </div>
                    <div class="input-field col s6">
                       <input placeholder="Longtitude" name="long" type="text">
                       <label for="long">Longtitude</label>
                    </div>
                </div>
                <div class="row">
                    <div class="file-field input-field col s12">
                        <div class="btn">
                            <span>File</span>
                            <input type="file" id="gambar" name="gambar[]" multiple>
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path" type="text" placeholder="Upload satu atau banyak gambar">
                        </div>
                    </div>
                </div>
                <div id="prev"></div>
                <div class="row">
                    <div class="input-field col s12">
                        <button type="submit" class="btn">Simpan</button>
                        <a href="{{ url('ketik/potensi') }}" class="btn waves-effect waves-light blue">Kembali</a>
                    </div>
                </div>
                </form>
           </div>
        </div>
    </div>


    <script src="{{ asset('js/jquery-3.3.1.min.js') }}" charset="utf-8"></script>
    <script type="text/javascript" src="{{ asset('js/materialize.min.js') }}"></script>
    <script type="text/javascript">
    if (window.File && window.FileList && window.FileReader) {
        $("#gambar").on("change", function(e) {
          var files = e.target.files,
            filesLength = files.length;
              for (var i = 0; i < filesLength; i++) {
                var f = files[i]
                var fileReader = new FileReader();
                fileReader.onload = (function(e) {
                  var file = e.target;
                  $("<div class='preview'><div class='card'>"+
                      "<div class='card-image'><img src='"+ e.target.result +"'>"+
                          "<span class='hapus'>x</span>"+
                      "</div></div></div>").appendTo('#prev');

                  $(".hapus").click(function(){
                      $(".preview").remove();
                      $(".file-path-wrapper input").val('');
                      $("#gambar").val("");
                  });

                });
                fileReader.readAsDataURL(f);
              }
            });
            } else {
                alert("Your browser doesn't support to File API")
            }
    </script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('select').formSelect();
        });
    </script>
</body>
</html>

resources/views/potensi/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dropzone</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{{ asset('css/materialize.min.css') }}"  media="screen,projection"/>
    <link rel="stylesheet" rel="stylesheet" href="{{ asset('css/styles.css') }}">
</head>
<body>

    <div class="container" style="margin-top: 40px;">
       <div class="card-panel">
           <div class="row">
               <span class="card-title">
                   <h5>Input Potensi</h5>
               </span>
                <form class="col s12" action="{{ url('/test') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="row">
                   <div class="input-field col s6">
                      <input placeholder="Nama Tempat" name="nama" type="text">
                      <label for="nama">Nama Tempat</label>
                   </div>
                   <div class="input-field col s6">
                      <input placeholder="Nama Pemilik" name="pemilik" type="text">
                      <label for="pemilik">Nama Pemilik</label>
                   </div>
                </div>
                <div class="row">
                   <div class="input-field col s12">
                      <input placeholder="Alamat" type="text" name="alamat">
                      <label for="alamat">Alamat</label>
                   </div>
                </div>
                <div class="row">
                   <div class="input-field col s12">
                      <textarea placeholder="Keterangan" id="keterangan" name="keterangan" class="materialize-textarea"></textarea>
                      <label for="keterangan">Keterangan</label>
                   </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                       <input placeholder="Latitude" name="lat" type="text">
                       <label for="lat">Latitude</label>
                    </div>
                    <div class="input-field col s6">
                       <input placeholder="Longtitude" name="long" type="text">
                       <label for="long">Longtitude</label>
                    </div>
                </div>
                <div class="row">
                    <div class="file-field input-field col s12">
                        <div class="btn">
                            <span>File</span>
                            <input type="file" id="gambar" name="gambar[]" multiple>
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text" placeholder="Upload satu atau banyak gambar">
                        </div>
                    </div>
                </div>
                <div id="prev"></div>
                <div class="row">
                    <div class="input-field col s12">
                        <button type="submit" class="btn">Simpan</button>
                    </div>
                </div>
                </form>
           </div>
        </div>
    </div>


    <script src="{{ asset('js/jquery-3.3.1.min.js') }}" charset="utf-8"></script>
    <script type="text/javascript" src="{{ asset('js/materialize.min.js') }}"></script>
    <script type="text/javascript">
    if (window.File && window.FileList && window.FileReader) {
        $("#gambar").on("change", function(e) {
          var files = e.target.files,
            filesLength = files.length;
              for (var i = 0; i < filesLength; i++) {
                var f = files[i]
                var fileReader = new FileReader();
                fileReader.onload = (function(e) {
                  var file = e.target;
                  $("<div class='preview'><div class='card'>"+
                      "<div class='card-image'><img src='"+ e.target.result +"'>"+
                          "<span class='hapus'>x</span>"+
                      "</div></div></div>").appendTo('#prev');

                  $(".hapus").click(function(){
                      $(".preview").remove();
                      $(".file-path-wrapper input").val('');
                      $("#gambar").val("");
                  });

                });
                fileReader.readAsDataURL(f);
              }
            });
            } else {
                alert("Your browser doesn't support to File API")
            }
    </script>
</body>
</html>

resources/views/potensi/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Data Potensi</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{{ asset('css/materialize.min.css') }}"  media="screen,projection"/>
    <link rel="stylesheet" rel="stylesheet" href="{{ asset('css/styles.css') }}">
</head>
<body>
    <div class="container-fluid" style="margin-top: 40px;">
       <div class="card-panel">
           <div class="row">
            <span class="card-title">
               <h5>Data Potensi</h5>
            </span>
            <a href="{{ url('ketik/potensi/create') }}" class="btn waves-effect waves-light">Buat Potensi</a>
            <table class="striped highlight">
                <thead>
                    <tr>
                        <th width="3%">No</th>
                        <th width="10%">Nama Tempat</th>
                        <th width="15%">Pemilik</th>
                        <th width="10%">Alamat</th>
                        <th width="50%">Keterangan</th>
                        <th width="7%">Kategori</th>
                        <th width="5%">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if(count($potensi) > 0)
                    <?php $no = 1; ?>
                    @foreach($potensi as $p)
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>{{ $p->nama }}</td>
                        <td>{{ $p->pemilik }}</td>
                        <td>{{ $p->alamat }}</td>
                        <td>{{ $p->keterangan }}</td>
                        <td>
                            @foreach($p->kategori as $kat)
                            <span class="new badge" data-badge-caption="{{ $kat->nama }}"></span>
                            @endforeach
                        </td>
                        <td>
                            <div class="action-btn">
                            <!-- <a href="{{ route('potensi.edit', $p->id) }}" class="waves-effect waves-light btn-small" title="Edit">
                                <i class="material-icons">create</i>
                            </a>
                            &nbsp;&nbsp; -->
                            <form action="{{ route('potensi.destroy',$p->id) }}" method="POST">
                                <input type="hidden" name="_method" value="DELETE">
                                {{ csrf_field() }}
                                <button class=" waves-effect waves-light btn-small" type="submit" title="Hapus">
                                    <i class="material-icons">delete</i>
                                </button>
                            </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                    @else
                    <tr>
                        <td colspan="6" class="center"><span>Data Potensi masih kosong.</span></td>
                    </tr>
                    @endif
                </tbody>
            </table>
           </div>
       </div>
    </div>
    <script src="{{ asset('js/jquery-3.3.1.min.js') }}" charset="utf-8"></script>
    <script type="text/javascript" src="{{ asset('js/materialize.min.js') }}"></script>
</body>
</html>