routes/web.php
<?php


Route::get('/', function () {
    $kategori = \App\Kategori::all();
    $potensi = \App\Potensi::with(['kategori', 'gambar'])->get()->toJson();
    // $potensi = $potensi->toJson(JSON_PRETTY_PRINT);

    return view('home', compact('kategori', 'potensi'));
});

Route::group(['prefix' => 'rute'], function() {
    Route::get('masyarakat', 'KunjunganController@masyarakat');
    Route::get('wilayah', 'KunjunganController@wilayah');
    Route::get('pkk1', 'KunjunganController@pkk1');
    Route::get('pkk2', 'KunjunganController@pkk2');
});

Route::resource('/ketik/potensi', 'PotensiController');
Route::resource('/ketik/kategori', 'KategoriController');

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    protected $table = 'kategori';

    public function potensi()
    {
        return $this->belongsToMany('\App\Potensi');
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kategori;
use Intervention\Image\ImageManagerStatic;
use Carbon\Carbon;

class KategoriController extends Controller
{
    protected $kategori;
    protected $image;
    protected $filename;
    protected $dest;

    public function __construct(Kategori $kategori, ImageManagerStatic $image)
    {
        $this->kategori = $kategori;
        $this->image = $image;
        $time = Carbon::now();
        $this->filename = str_random(5).date_format($time,'d').rand(1,9).date_format($time,'h').".png";
        $this->dest = public_path('images/icons');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = $this->kategori->all();

        return view('kategori.index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->hasFile('gambar')) {
            $image = $request->file('gambar');

            if (!file_exists($this->dest)) {
                mkdir($this->dest, 666, true);
            }

            $image = $this->image->make($image)->save($this->dest.'/'.$this->filename);
            $this->kategori->gambar_icon = $this->filename;
        }

        $this->kategori->nama = $request->nama;
        $this->kategori->deskripsi = $request->deskripsi;
        $kategori = $this->kategori->save();

        return redirect('ketik/kategori');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = $this->kategori->find($id);

        return view('kategori.edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());
        $kategori = $this->kategori->find($id);

        // jika gambar diganti
        if($request->hasFile('gambar')) {
            // delete file sebelumnya
            unlink($this->dest.'/'.$kategori->gambar_icon);
            $image = $request->file('gambar');
            $image = $this->image->make($image)->save($this->dest.'/'.$this->filename);
            $kategori->gambar_icon = $this->filename;
        }

        $kategori->nama = $request->nama;
        $kategori->deskripsi = $request->deskripsi;
        $kategori->save();

        return redirect('ketik/kategori');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kategori = $this->kategori->find($id);
        if($kategori->gambar_icon) {
            unlink($this->dest.'/'.$kategori->gambar_icon);
        }
        $kategori->potensi()->wherePivot('kategori_id', '=', $id)->detach();
        $kategori->delete();

        return redirect('ketik/kategori');
    }
}

resources/views/kategori/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Buat Kategori</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{{ asset('css/materialize.min.css') }}"  media="screen,projection"/>
    <link rel="stylesheet" rel="stylesheet" href="{{ asset('css/styles.css') }}">
</head>
<body>

    <div class="container" style="margin-top: 40px;">
       <div class="card-panel">
           <div class="row">
               <span class="card-title">
                   <h5>Buat Kategori</h5>
               </span>
                <form class="col s12" action="{{ url('/ketik/kategori') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="row">
                   <div class="input-field col s12">
                      <input placeholder="Nama Kategori" name="nama" type="text">
                      <label for="nama">Nama Kategori</label>
                   </div>
                </div>
                <div class="row">
                   <div class="input-field col s12">
                      <input placeholder="Deskripsi" type="text" name="deskripsi">
                      <label for="deskripsi">Deskripsi</label>
                   </div>
               </div>
                <div class="row">
                    <div class="file-field input-field col s12">
                        <div class="btn">
                            <span>File</span>
                            <input type="file" id="gambar" name="gambar">
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path" type="text" placeholder="Upload icon berbentuk png">
                        </div>
                    </div>
                </div>
                <div id="prev"></div>
                <div class="row">
                    <div class="input-field col s12">
                        <button type="submit"  class="btn waves-effect waves-light">Simpan</button>
                        <a href="{{ url('ketik/kategori') }}" class="btn waves-effect waves-light blue">Kembali</a>
                    </div>
                </div>
                </form>
           </div>
        </div>
    </div>

    <script src="{{ asset('js/jquery-3.3.1.min.js') }}" charset="utf-8"></script>
    <script type="text/javascript" src="{{ asset('js/materialize.min.js') }}"></script>
</body>
</html>

resources/views/kategori/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit Kategori</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{{ asset('css/materialize.min.css') }}"  media="screen,projection"/>
    <link rel="stylesheet" rel="stylesheet" href="{{ asset('css/styles.css') }}">
</head>
<body>

    <div class="container" style="margin-top: 40px;">
       <div class="card-panel">
           <div class="row">
               <span class="card-title">
                   <h5>Edit Kategori</h5>
               </span>
                <form class="col s12" action="{{ url('/ketik/kategori/'.$kategori->id) }}" method="post" enctype="multipart/form-data">
                <input type="hidden" name="_method" value="PUT">
                {{ csrf_field() }}
                <div class="row">
                   <div class="input-field col s12">
                      <input placeholder="Nama Kategori" name="nama" type="text" value="{{ $kategori->nama }}">
                      <label for="nama">Nama Kategori</label>
                   </div>
                </div>
                <div class="row">
                   <div class="input-field col s12">
                      <input placeholder="Deskripsi" type="text" name="deskripsi" value="{{ $kategori->deskripsi }}">
                      <label for="deskripsi">Deskripsi</label>
                   </div>
               </div>
                <div class="row">
                    <div class="file-field input-field col s12">
                        <div class="btn">
                            <span>File</span>
                            <input type="file" id="gambar" name="gambar">
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path" type="text" placeholder="Upload icon berbentuk png">
                        </div>
                    </div>
                </div>
                <div id="prev"></div>
                <div class="row">
                    <div class="input-field col s12">
                        <button type="submit" class="btn">Update</button>
                        <a href="{{ url('ketik/kategori') }}" class="btn waves-effect waves-light blue">Kembali</a>
                    </div>
                </div>
                </form>
           </div>
        </div>
    </div>

    <script src="{{ asset('js/jquery-3.3.1.min.js') }}" charset="utf-8"></script>
    <script type="text/javascript" src="{{ asset('js/materialize.min.js') }}"></script>
</body>
</html>

resources/views/kategori/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Data Kategori</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{{ asset('css/materialize.min.css') }}"  media="screen,projection"/>
    <link rel="stylesheet" rel="stylesheet" href="{{ asset('css/styles.css') }}">
</head>
<body>
    <div class="container" style="margin-top: 40px;">
       <div class="card-panel">
           <div class="row">
            <span class="card-title">
               <h5>Data Kategori</h5>
            </span>
            <a href="{{ url('ketik/kategori/create') }}" class="btn waves-effect waves-light">Buat Kategori</a>
            <table class="striped highlight">
                <thead>
                    <tr>
                        <th>Nama Kategori</th>
                        <th>Deskripsi</th>
                        <th>Gambar Icon</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if(count($kategori)> 0)
                    @foreach($kategori as $kat)
                    <tr>
                        <td>{{ $kat->nama }}</td>
                        <td>{{ $kat->deskripsi }}</td>
                        <td>@if($kat->gambar_icon)<img src="{{ asset('images/icons/'.$kat->gambar_icon) }}" alt="">@endif</td>
                        <td>
                            <div class="action-btn">
                            <a href="{{ route('kategori.edit', $kat->id) }}" class="waves-effect waves-light btn-small" title="Edit">
                                <i class="material-icons">create</i>
                            </a>
                            &nbsp;&nbsp;
                            <form action="{{ route('kategori.destroy',$kat->id) }}" method="POST">
                                <input type="hidden" name="_method" value="DELETE">
                                {{ csrf_field() }}
                                <button class=" waves-effect waves-light btn-small" type="submit" title="Hapus">
                                    <i class="material-icons">delete</i>
                                </button>
                            </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                    @else
                    <tr>
                        <td colspan="4" class="center"><span>Data kategori masih kosong.</span></td>
                    </tr>
                    @endif
                </tbody>
            </table>
           </div>
       </div>
    </div>
    <script src="{{ asset('js/jquery-3.3.1.min.js') }}" charset="utf-8"></script>
    <script type="text/javascript" src="{{ asset('js/materialize.min.js') }}"></script>
</body>
</html>